### ISSUE TITLE
possible segmentation fault

### ISSUE THREAD

**Issue by spedygiorgio** [krlmlr/bindrcpp#4]
Hi, on my travis ci [travis](https://travis-ci.org/spedygiorgio/markovchain) an error is raised after bindrcpp is installed...
```
Installing bindrcpp
 *** caught segfault ***
address 0xfffffff9, cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...
/home/travis/.travis/job_stages: line 54: 13342 Segmentation fault      (core dumped) Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 139 during .
Your build has been stopped.
```

Is it possible a problem arise from your package?

**Comment by krlmlr** [comment]
Thank you very much for reporting. This is the first time I ever see a segfault during package installation. Something very strange is going on, but I don't think this is bindrcpp's fault. Can you please rerun the build?

**Comment by krlmlr** [comment]
Just seen it on one of my machines. Will observe.

**Comment by gaborcsardi** [comment]
What version of `devtools`?

**Comment by gaborcsardi** [comment]
And where is the Travis job, actually?

**Comment by krlmlr** [comment]
https://travis-ci.org/spedygiorgio/markovchain/builds/242031968 is one.

**Comment by gaborcsardi** [comment]
shot in the dark: cached incompatible build time dependency: bindr ?

**Comment by gaborcsardi** [comment]
Or Rcpp?

Anyway, I would try with a clean cache....

**Comment by bbolker** [comment]
Just a heads-up, still investigating.  Was seeing some segfaults running tests for the `broom.mixed` package locally (GH repo [here](https://github.com/bbolker/broom.mixed)), that seemed to trace back to `bindrcpp`. `devtools::test()` or `source("tests/testthat/test-lme4.R")` 

 Now they've gone away (kinda heisenbuggy ...) but I'll report here if they recur.

**Comment by krlmlr** [comment]
_bindrcpp_ is going away in dplyr 0.8.0 (already gone in the dev version), and is replaced by a reimplementation based on similar principles.
