### ISSUE TITLE
Could not find Makevars.local

### ISSUE THREAD

**Issue by wenheping** [krlmlr/bindrcpp#5]
I failed build R package bindrcpp ob FreeBSD with the error message  :

make[1]: "/usr/ports/devel/R-cran-bindrcpp/work/bindrcpp/src/Makevars" line 9: Could not find Makevars.local

I download the package from CRAN mirrors, seems Makevars.local file had not been included into package, while it exists in your github repo.

**Comment by krlmlr** [comment]
Thanks for reporting. I'm about to release an update to CRAN which will not contain the reference to `Makevars.local` anymore.
