### ISSUE TITLE
Support R objects as payload

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/bindrcpp#7]
so that we don't need to worry about ownership and lifetime.

**Comment by krlmlr** [comment]
@jayhesselberth: Please let me know if *valr* still works with this update, I'm planning to release to CRAN soon. (`PAYLOAD` was an awfully bad idea, I suggest to take advantage of this patch and pass `List` objects instead. With `PAYLOAD` you never know for sure when you may destroy the object that is hidden behind the `void*`.)

**Comment by jayhesselberth** [comment]
This will take some digging. I packaged dplyr headers in valr and use of PAYLOAD is restricted to the dplyr header files. I just tried to compile against the current dplyr headers but I'm getting errors relating to build_index_cpp and ambiguous DataFrameSubsetVisitors. Will try to fix by the end of the week.

**Comment by krlmlr** [comment]
Oh, I see. I moved the implementation of `DataFrameSubsetVisitors` to a translation unit, but you should be able to use the older dplyr headers -- *bindrcpp* should remain compatible.
